USE [master]
GO

/****** Object:  Database [SalesManagmentSystem]    Script Date: 15/04/2020 21:54:13 ******/
CREATE DATABASE [SalesManagmentSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SalesManagmentSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SalesManagmentSystem.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SalesManagmentSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SalesManagmentSystem_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SalesManagmentSystem] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SalesManagmentSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SalesManagmentSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SalesManagmentSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SalesManagmentSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SalesManagmentSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [SalesManagmentSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SalesManagmentSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SalesManagmentSystem] SET  MULTI_USER 
GO

ALTER DATABASE [SalesManagmentSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SalesManagmentSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SalesManagmentSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SalesManagmentSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SalesManagmentSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SalesManagmentSystem] SET  READ_WRITE 
GO

