#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation_Layer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SalesManagmentSystem")]
	public partial class SalesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertaccounts(accounts instance);
    partial void Updateaccounts(accounts instance);
    partial void Deleteaccounts(accounts instance);
    partial void Insertunits(units instance);
    partial void Updateunits(units instance);
    partial void Deleteunits(units instance);
    partial void Insertcompany_info(company_info instance);
    partial void Updatecompany_info(company_info instance);
    partial void Deletecompany_info(company_info instance);
    partial void Insertcustomers_suppliers(customers_suppliers instance);
    partial void Updatecustomers_suppliers(customers_suppliers instance);
    partial void Deletecustomers_suppliers(customers_suppliers instance);
    partial void Insertinvoices_details(invoices_details instance);
    partial void Updateinvoices_details(invoices_details instance);
    partial void Deleteinvoices_details(invoices_details instance);
    partial void Insertinvoices_header(invoices_header instance);
    partial void Updateinvoices_header(invoices_header instance);
    partial void Deleteinvoices_header(invoices_header instance);
    partial void Insertproduct_categories(product_categories instance);
    partial void Updateproduct_categories(product_categories instance);
    partial void Deleteproduct_categories(product_categories instance);
    partial void Insertproducts(products instance);
    partial void Updateproducts(products instance);
    partial void Deleteproducts(products instance);
    partial void Insertproducts_units(products_units instance);
    partial void Updateproducts_units(products_units instance);
    partial void Deleteproducts_units(products_units instance);
    partial void InsertStores_records(Stores_records instance);
    partial void UpdateStores_records(Stores_records instance);
    partial void DeleteStores_records(Stores_records instance);
    partial void Inserttreasurys(treasurys instance);
    partial void Updatetreasurys(treasurys instance);
    partial void Deletetreasurys(treasurys instance);
    partial void Insertjournals(journals instance);
    partial void Updatejournals(journals instance);
    partial void Deletejournals(journals instance);
    partial void Insertstores(stores instance);
    partial void Updatestores(stores instance);
    partial void Deletestores(stores instance);
    #endregion
		
		public SalesDataContext() : 
				base(global::Presentation_Layer.Properties.Settings.Default.SalesManagmentSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SalesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<accounts> accounts
		{
			get
			{
				return this.GetTable<accounts>();
			}
		}
		
		public System.Data.Linq.Table<units> units
		{
			get
			{
				return this.GetTable<units>();
			}
		}
		
		public System.Data.Linq.Table<company_info> company_info
		{
			get
			{
				return this.GetTable<company_info>();
			}
		}
		
		public System.Data.Linq.Table<customers_suppliers> customers_suppliers
		{
			get
			{
				return this.GetTable<customers_suppliers>();
			}
		}
		
		public System.Data.Linq.Table<invoices_details> invoices_details
		{
			get
			{
				return this.GetTable<invoices_details>();
			}
		}
		
		public System.Data.Linq.Table<invoices_header> invoices_header
		{
			get
			{
				return this.GetTable<invoices_header>();
			}
		}
		
		public System.Data.Linq.Table<product_categories> product_categories
		{
			get
			{
				return this.GetTable<product_categories>();
			}
		}
		
		public System.Data.Linq.Table<products> products
		{
			get
			{
				return this.GetTable<products>();
			}
		}
		
		public System.Data.Linq.Table<products_units> products_units
		{
			get
			{
				return this.GetTable<products_units>();
			}
		}
		
		public System.Data.Linq.Table<Stores_records> Stores_records
		{
			get
			{
				return this.GetTable<Stores_records>();
			}
		}
		
		public System.Data.Linq.Table<treasurys> treasurys
		{
			get
			{
				return this.GetTable<treasurys>();
			}
		}
		
		public System.Data.Linq.Table<journals> journals
		{
			get
			{
				return this.GetTable<journals>();
			}
		}
		
		public System.Data.Linq.Table<stores> stores
		{
			get
			{
				return this.GetTable<stores>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.accounts")]
	public partial class accounts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public accounts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.units")]
	public partial class units : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public units()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.company_info")]
	public partial class company_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _company_id;
		
		private string _company_name;
		
		private string _company_address;
		
		private string _company_mobile;
		
		private string _company_email;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncompany_idChanging(int value);
    partial void Oncompany_idChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Oncompany_addressChanging(string value);
    partial void Oncompany_addressChanged();
    partial void Oncompany_mobileChanging(string value);
    partial void Oncompany_mobileChanged();
    partial void Oncompany_emailChanging(string value);
    partial void Oncompany_emailChanged();
    #endregion
		
		public company_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int company_id
		{
			get
			{
				return this._company_id;
			}
			set
			{
				if ((this._company_id != value))
				{
					this.Oncompany_idChanging(value);
					this.SendPropertyChanging();
					this._company_id = value;
					this.SendPropertyChanged("company_id");
					this.Oncompany_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_address", DbType="NVarChar(MAX)")]
		public string company_address
		{
			get
			{
				return this._company_address;
			}
			set
			{
				if ((this._company_address != value))
				{
					this.Oncompany_addressChanging(value);
					this.SendPropertyChanging();
					this._company_address = value;
					this.SendPropertyChanged("company_address");
					this.Oncompany_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_mobile", DbType="NVarChar(MAX)")]
		public string company_mobile
		{
			get
			{
				return this._company_mobile;
			}
			set
			{
				if ((this._company_mobile != value))
				{
					this.Oncompany_mobileChanging(value);
					this.SendPropertyChanging();
					this._company_mobile = value;
					this.SendPropertyChanged("company_mobile");
					this.Oncompany_mobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_email", DbType="NVarChar(MAX)")]
		public string company_email
		{
			get
			{
				return this._company_email;
			}
			set
			{
				if ((this._company_email != value))
				{
					this.Oncompany_emailChanging(value);
					this.SendPropertyChanging();
					this._company_email = value;
					this.SendPropertyChanged("company_email");
					this.Oncompany_emailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers_suppliers")]
	public partial class customers_suppliers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _address;
		
		private string _mobile;
		
		private string _email;
		
		private bool _Iscustomer;
		
		private int _account_id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnIscustomerChanging(bool value);
    partial void OnIscustomerChanged();
    partial void Onaccount_idChanging(int value);
    partial void Onaccount_idChanged();
    #endregion
		
		public customers_suppliers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(MAX)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iscustomer", DbType="Bit NOT NULL")]
		public bool Iscustomer
		{
			get
			{
				return this._Iscustomer;
			}
			set
			{
				if ((this._Iscustomer != value))
				{
					this.OnIscustomerChanging(value);
					this.SendPropertyChanging();
					this._Iscustomer = value;
					this.SendPropertyChanged("Iscustomer");
					this.OnIscustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int NOT NULL")]
		public int account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.invoices_details")]
	public partial class invoices_details : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _invoiceid;
		
		private int _itemid;
		
		private int _itemunit_id;
		
		private double _item_Qty;
		
		private double _price;
		
		private double _total_price;
		
		private double _cost_value;
		
		private double _totalcoste_value;
		
		private double _discount;
		
		private double _discount_value;
		
		private int _store_id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OninvoiceidChanging(int value);
    partial void OninvoiceidChanged();
    partial void OnitemidChanging(int value);
    partial void OnitemidChanged();
    partial void Onitemunit_idChanging(int value);
    partial void Onitemunit_idChanged();
    partial void Onitem_QtyChanging(double value);
    partial void Onitem_QtyChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void Ontotal_priceChanging(double value);
    partial void Ontotal_priceChanged();
    partial void Oncost_valueChanging(double value);
    partial void Oncost_valueChanged();
    partial void Ontotalcoste_valueChanging(double value);
    partial void Ontotalcoste_valueChanged();
    partial void OndiscountChanging(double value);
    partial void OndiscountChanged();
    partial void Ondiscount_valueChanging(double value);
    partial void Ondiscount_valueChanged();
    partial void Onstore_idChanging(int value);
    partial void Onstore_idChanged();
    #endregion
		
		public invoices_details()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceid", DbType="Int NOT NULL")]
		public int invoiceid
		{
			get
			{
				return this._invoiceid;
			}
			set
			{
				if ((this._invoiceid != value))
				{
					this.OninvoiceidChanging(value);
					this.SendPropertyChanging();
					this._invoiceid = value;
					this.SendPropertyChanged("invoiceid");
					this.OninvoiceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int NOT NULL")]
		public int itemid
		{
			get
			{
				return this._itemid;
			}
			set
			{
				if ((this._itemid != value))
				{
					this.OnitemidChanging(value);
					this.SendPropertyChanging();
					this._itemid = value;
					this.SendPropertyChanged("itemid");
					this.OnitemidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemunit_id", DbType="Int NOT NULL")]
		public int itemunit_id
		{
			get
			{
				return this._itemunit_id;
			}
			set
			{
				if ((this._itemunit_id != value))
				{
					this.Onitemunit_idChanging(value);
					this.SendPropertyChanging();
					this._itemunit_id = value;
					this.SendPropertyChanged("itemunit_id");
					this.Onitemunit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_Qty", DbType="Float NOT NULL")]
		public double item_Qty
		{
			get
			{
				return this._item_Qty;
			}
			set
			{
				if ((this._item_Qty != value))
				{
					this.Onitem_QtyChanging(value);
					this.SendPropertyChanging();
					this._item_Qty = value;
					this.SendPropertyChanged("item_Qty");
					this.Onitem_QtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Float NOT NULL")]
		public double total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this.Ontotal_priceChanging(value);
					this.SendPropertyChanging();
					this._total_price = value;
					this.SendPropertyChanged("total_price");
					this.Ontotal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_value", DbType="Float NOT NULL")]
		public double cost_value
		{
			get
			{
				return this._cost_value;
			}
			set
			{
				if ((this._cost_value != value))
				{
					this.Oncost_valueChanging(value);
					this.SendPropertyChanging();
					this._cost_value = value;
					this.SendPropertyChanged("cost_value");
					this.Oncost_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalcoste_value", DbType="Float NOT NULL")]
		public double totalcoste_value
		{
			get
			{
				return this._totalcoste_value;
			}
			set
			{
				if ((this._totalcoste_value != value))
				{
					this.Ontotalcoste_valueChanging(value);
					this.SendPropertyChanging();
					this._totalcoste_value = value;
					this.SendPropertyChanged("totalcoste_value");
					this.Ontotalcoste_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Float NOT NULL")]
		public double discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_value", DbType="Float NOT NULL")]
		public double discount_value
		{
			get
			{
				return this._discount_value;
			}
			set
			{
				if ((this._discount_value != value))
				{
					this.Ondiscount_valueChanging(value);
					this.SendPropertyChanging();
					this._discount_value = value;
					this.SendPropertyChanged("discount_value");
					this.Ondiscount_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int NOT NULL")]
		public int store_id
		{
			get
			{
				return this._store_id;
			}
			set
			{
				if ((this._store_id != value))
				{
					this.Onstore_idChanging(value);
					this.SendPropertyChanging();
					this._store_id = value;
					this.SendPropertyChanged("store_id");
					this.Onstore_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.invoices_header")]
	public partial class invoices_header : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private byte _invoice_type;
		
		private string _code;
		
		private byte _part_type;
		
		private int _part_id;
		
		private System.DateTime _date;
		
		private System.Nullable<System.DateTime> _delivery_date;
		
		private int _branch;
		
		private string _notes;
		
		private System.Nullable<System.DateTime> _post_date;
		
		private bool _posted_tostore;
		
		private double _total;
		
		private double _discount_value;
		
		private double _discount_ratio;
		
		private double _tax;
		
		private double _tax_value;
		
		private double _expences;
		
		private double _net;
		
		private double _paid;
		
		private double _remaing;
		
		private int _treasurys;
		
		private string _shippment_address;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oninvoice_typeChanging(byte value);
    partial void Oninvoice_typeChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onpart_typeChanging(byte value);
    partial void Onpart_typeChanged();
    partial void Onpart_idChanging(int value);
    partial void Onpart_idChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Ondelivery_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelivery_dateChanged();
    partial void OnbranchChanging(int value);
    partial void OnbranchChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    partial void Onpost_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onpost_dateChanged();
    partial void Onposted_tostoreChanging(bool value);
    partial void Onposted_tostoreChanged();
    partial void OntotalChanging(double value);
    partial void OntotalChanged();
    partial void Ondiscount_valueChanging(double value);
    partial void Ondiscount_valueChanged();
    partial void Ondiscount_ratioChanging(double value);
    partial void Ondiscount_ratioChanged();
    partial void OntaxChanging(double value);
    partial void OntaxChanged();
    partial void Ontax_valueChanging(double value);
    partial void Ontax_valueChanged();
    partial void OnexpencesChanging(double value);
    partial void OnexpencesChanged();
    partial void OnnetChanging(double value);
    partial void OnnetChanged();
    partial void OnpaidChanging(double value);
    partial void OnpaidChanged();
    partial void OnremaingChanging(double value);
    partial void OnremaingChanged();
    partial void OntreasurysChanging(int value);
    partial void OntreasurysChanged();
    partial void Onshippment_addressChanging(string value);
    partial void Onshippment_addressChanged();
    #endregion
		
		public invoices_header()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoice_type", DbType="TinyInt NOT NULL")]
		public byte invoice_type
		{
			get
			{
				return this._invoice_type;
			}
			set
			{
				if ((this._invoice_type != value))
				{
					this.Oninvoice_typeChanging(value);
					this.SendPropertyChanging();
					this._invoice_type = value;
					this.SendPropertyChanged("invoice_type");
					this.Oninvoice_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_type", DbType="TinyInt NOT NULL")]
		public byte part_type
		{
			get
			{
				return this._part_type;
			}
			set
			{
				if ((this._part_type != value))
				{
					this.Onpart_typeChanging(value);
					this.SendPropertyChanging();
					this._part_type = value;
					this.SendPropertyChanged("part_type");
					this.Onpart_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", DbType="Int NOT NULL")]
		public int part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this.Onpart_idChanging(value);
					this.SendPropertyChanging();
					this._part_id = value;
					this.SendPropertyChanged("part_id");
					this.Onpart_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delivery_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> delivery_date
		{
			get
			{
				return this._delivery_date;
			}
			set
			{
				if ((this._delivery_date != value))
				{
					this.Ondelivery_dateChanging(value);
					this.SendPropertyChanging();
					this._delivery_date = value;
					this.SendPropertyChanged("delivery_date");
					this.Ondelivery_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch", DbType="Int NOT NULL")]
		public int branch
		{
			get
			{
				return this._branch;
			}
			set
			{
				if ((this._branch != value))
				{
					this.OnbranchChanging(value);
					this.SendPropertyChanging();
					this._branch = value;
					this.SendPropertyChanged("branch");
					this.OnbranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> post_date
		{
			get
			{
				return this._post_date;
			}
			set
			{
				if ((this._post_date != value))
				{
					this.Onpost_dateChanging(value);
					this.SendPropertyChanging();
					this._post_date = value;
					this.SendPropertyChanged("post_date");
					this.Onpost_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posted_tostore", DbType="Bit NOT NULL")]
		public bool posted_tostore
		{
			get
			{
				return this._posted_tostore;
			}
			set
			{
				if ((this._posted_tostore != value))
				{
					this.Onposted_tostoreChanging(value);
					this.SendPropertyChanging();
					this._posted_tostore = value;
					this.SendPropertyChanged("posted_tostore");
					this.Onposted_tostoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float NOT NULL")]
		public double total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_value", DbType="Float NOT NULL")]
		public double discount_value
		{
			get
			{
				return this._discount_value;
			}
			set
			{
				if ((this._discount_value != value))
				{
					this.Ondiscount_valueChanging(value);
					this.SendPropertyChanging();
					this._discount_value = value;
					this.SendPropertyChanged("discount_value");
					this.Ondiscount_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_ratio", DbType="Float NOT NULL")]
		public double discount_ratio
		{
			get
			{
				return this._discount_ratio;
			}
			set
			{
				if ((this._discount_ratio != value))
				{
					this.Ondiscount_ratioChanging(value);
					this.SendPropertyChanging();
					this._discount_ratio = value;
					this.SendPropertyChanged("discount_ratio");
					this.Ondiscount_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax", DbType="Float NOT NULL")]
		public double tax
		{
			get
			{
				return this._tax;
			}
			set
			{
				if ((this._tax != value))
				{
					this.OntaxChanging(value);
					this.SendPropertyChanging();
					this._tax = value;
					this.SendPropertyChanged("tax");
					this.OntaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax_value", DbType="Float NOT NULL")]
		public double tax_value
		{
			get
			{
				return this._tax_value;
			}
			set
			{
				if ((this._tax_value != value))
				{
					this.Ontax_valueChanging(value);
					this.SendPropertyChanging();
					this._tax_value = value;
					this.SendPropertyChanged("tax_value");
					this.Ontax_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expences", DbType="Float NOT NULL")]
		public double expences
		{
			get
			{
				return this._expences;
			}
			set
			{
				if ((this._expences != value))
				{
					this.OnexpencesChanging(value);
					this.SendPropertyChanging();
					this._expences = value;
					this.SendPropertyChanged("expences");
					this.OnexpencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_net", DbType="Float NOT NULL")]
		public double net
		{
			get
			{
				return this._net;
			}
			set
			{
				if ((this._net != value))
				{
					this.OnnetChanging(value);
					this.SendPropertyChanging();
					this._net = value;
					this.SendPropertyChanged("net");
					this.OnnetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Float NOT NULL")]
		public double paid
		{
			get
			{
				return this._paid;
			}
			set
			{
				if ((this._paid != value))
				{
					this.OnpaidChanging(value);
					this.SendPropertyChanging();
					this._paid = value;
					this.SendPropertyChanged("paid");
					this.OnpaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remaing", DbType="Float NOT NULL")]
		public double remaing
		{
			get
			{
				return this._remaing;
			}
			set
			{
				if ((this._remaing != value))
				{
					this.OnremaingChanging(value);
					this.SendPropertyChanging();
					this._remaing = value;
					this.SendPropertyChanged("remaing");
					this.OnremaingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treasurys", DbType="Int NOT NULL")]
		public int treasurys
		{
			get
			{
				return this._treasurys;
			}
			set
			{
				if ((this._treasurys != value))
				{
					this.OntreasurysChanging(value);
					this.SendPropertyChanging();
					this._treasurys = value;
					this.SendPropertyChanged("treasurys");
					this.OntreasurysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippment_address", DbType="NVarChar(MAX)")]
		public string shippment_address
		{
			get
			{
				return this._shippment_address;
			}
			set
			{
				if ((this._shippment_address != value))
				{
					this.Onshippment_addressChanging(value);
					this.SendPropertyChanging();
					this._shippment_address = value;
					this.SendPropertyChanged("shippment_address");
					this.Onshippment_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_categories")]
	public partial class product_categories : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _parent_id;
		
		private string _name;
		
		private string _number;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onparent_idChanging(int value);
    partial void Onparent_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnumberChanging(string value);
    partial void OnnumberChanged();
    #endregion
		
		public product_categories()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products")]
	public partial class products : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _code;
		
		private string _Name;
		
		private int _type;
		
		private string _details;
		
		private bool _status;
		
		private System.Data.Linq.Binary _image;
		
		private int _category_id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    #endregion
		
		public products()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX)")]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this.OndetailsChanging(value);
					this.SendPropertyChanging();
					this._details = value;
					this.SendPropertyChanged("details");
					this.OndetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products_units")]
	public partial class products_units : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _productid;
		
		private int _unitid;
		
		private double _factor;
		
		private double _buyprice;
		
		private double _sellprice;
		
		private double _selldiscount;
		
		private string _barcode;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnproductidChanging(int value);
    partial void OnproductidChanged();
    partial void OnunitidChanging(int value);
    partial void OnunitidChanged();
    partial void OnfactorChanging(double value);
    partial void OnfactorChanged();
    partial void OnbuypriceChanging(double value);
    partial void OnbuypriceChanged();
    partial void OnsellpriceChanging(double value);
    partial void OnsellpriceChanged();
    partial void OnselldiscountChanging(double value);
    partial void OnselldiscountChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    #endregion
		
		public products_units()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", DbType="Int NOT NULL")]
		public int productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					this.OnproductidChanging(value);
					this.SendPropertyChanging();
					this._productid = value;
					this.SendPropertyChanged("productid");
					this.OnproductidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitid", DbType="Int NOT NULL")]
		public int unitid
		{
			get
			{
				return this._unitid;
			}
			set
			{
				if ((this._unitid != value))
				{
					this.OnunitidChanging(value);
					this.SendPropertyChanging();
					this._unitid = value;
					this.SendPropertyChanged("unitid");
					this.OnunitidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factor", DbType="Float NOT NULL")]
		public double factor
		{
			get
			{
				return this._factor;
			}
			set
			{
				if ((this._factor != value))
				{
					this.OnfactorChanging(value);
					this.SendPropertyChanging();
					this._factor = value;
					this.SendPropertyChanged("factor");
					this.OnfactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buyprice", DbType="Float NOT NULL")]
		public double buyprice
		{
			get
			{
				return this._buyprice;
			}
			set
			{
				if ((this._buyprice != value))
				{
					this.OnbuypriceChanging(value);
					this.SendPropertyChanging();
					this._buyprice = value;
					this.SendPropertyChanged("buyprice");
					this.OnbuypriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sellprice", DbType="Float NOT NULL")]
		public double sellprice
		{
			get
			{
				return this._sellprice;
			}
			set
			{
				if ((this._sellprice != value))
				{
					this.OnsellpriceChanging(value);
					this.SendPropertyChanging();
					this._sellprice = value;
					this.SendPropertyChanged("sellprice");
					this.OnsellpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selldiscount", DbType="Float NOT NULL")]
		public double selldiscount
		{
			get
			{
				return this._selldiscount;
			}
			set
			{
				if ((this._selldiscount != value))
				{
					this.OnselldiscountChanging(value);
					this.SendPropertyChanging();
					this._selldiscount = value;
					this.SendPropertyChanged("selldiscount");
					this.OnselldiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stores_records")]
	public partial class Stores_records : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private byte _source_type;
		
		private int _source_id;
		
		private int _product_id;
		
		private int _store_id;
		
		private double _qty;
		
		private string _store_transaction;
		
		private double _costvalue;
		
		private System.DateTime _inserttime;
		
		private string _notes;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsource_typeChanging(byte value);
    partial void Onsource_typeChanged();
    partial void Onsource_idChanging(int value);
    partial void Onsource_idChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onstore_idChanging(int value);
    partial void Onstore_idChanged();
    partial void OnqtyChanging(double value);
    partial void OnqtyChanged();
    partial void Onstore_transactionChanging(string value);
    partial void Onstore_transactionChanged();
    partial void OncostvalueChanging(double value);
    partial void OncostvalueChanged();
    partial void OninserttimeChanging(System.DateTime value);
    partial void OninserttimeChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
		
		public Stores_records()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_type", DbType="TinyInt NOT NULL")]
		public byte source_type
		{
			get
			{
				return this._source_type;
			}
			set
			{
				if ((this._source_type != value))
				{
					this.Onsource_typeChanging(value);
					this.SendPropertyChanging();
					this._source_type = value;
					this.SendPropertyChanged("source_type");
					this.Onsource_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_id", DbType="Int NOT NULL")]
		public int source_id
		{
			get
			{
				return this._source_id;
			}
			set
			{
				if ((this._source_id != value))
				{
					this.Onsource_idChanging(value);
					this.SendPropertyChanging();
					this._source_id = value;
					this.SendPropertyChanged("source_id");
					this.Onsource_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int NOT NULL")]
		public int store_id
		{
			get
			{
				return this._store_id;
			}
			set
			{
				if ((this._store_id != value))
				{
					this.Onstore_idChanging(value);
					this.SendPropertyChanging();
					this._store_id = value;
					this.SendPropertyChanged("store_id");
					this.Onstore_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Float NOT NULL")]
		public double qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_transaction", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string store_transaction
		{
			get
			{
				return this._store_transaction;
			}
			set
			{
				if ((this._store_transaction != value))
				{
					this.Onstore_transactionChanging(value);
					this.SendPropertyChanging();
					this._store_transaction = value;
					this.SendPropertyChanged("store_transaction");
					this.Onstore_transactionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costvalue", DbType="Float NOT NULL")]
		public double costvalue
		{
			get
			{
				return this._costvalue;
			}
			set
			{
				if ((this._costvalue != value))
				{
					this.OncostvalueChanging(value);
					this.SendPropertyChanging();
					this._costvalue = value;
					this.SendPropertyChanged("costvalue");
					this.OncostvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inserttime", DbType="DateTime NOT NULL")]
		public System.DateTime inserttime
		{
			get
			{
				return this._inserttime;
			}
			set
			{
				if ((this._inserttime != value))
				{
					this.OninserttimeChanging(value);
					this.SendPropertyChanging();
					this._inserttime = value;
					this.SendPropertyChanged("inserttime");
					this.OninserttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.treasurys")]
	public partial class treasurys : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<int> _account_id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onaccount_idChanging(System.Nullable<int> value);
    partial void Onaccount_idChanged();
    #endregion
		
		public treasurys()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int")]
		public System.Nullable<int> account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.journals")]
	public partial class journals : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _Code;
		
		private int _AccountID;
		
		private double _Debit;
		
		private double _Credit;
		
		private System.DateTime _InsertDate;
		
		private byte _SourceType;
		
		private int _SourceID;
		
		private string _Notes;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnCodeChanging(long value);
    partial void OnCodeChanged();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnDebitChanging(double value);
    partial void OnDebitChanged();
    partial void OnCreditChanging(double value);
    partial void OnCreditChanged();
    partial void OnInsertDateChanging(System.DateTime value);
    partial void OnInsertDateChanged();
    partial void OnSourceTypeChanging(byte value);
    partial void OnSourceTypeChanged();
    partial void OnSourceIDChanging(int value);
    partial void OnSourceIDChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public journals()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="BigInt NOT NULL")]
		public long Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int NOT NULL")]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debit", DbType="Float NOT NULL")]
		public double Debit
		{
			get
			{
				return this._Debit;
			}
			set
			{
				if ((this._Debit != value))
				{
					this.OnDebitChanging(value);
					this.SendPropertyChanging();
					this._Debit = value;
					this.SendPropertyChanged("Debit");
					this.OnDebitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Credit", DbType="Float NOT NULL")]
		public double Credit
		{
			get
			{
				return this._Credit;
			}
			set
			{
				if ((this._Credit != value))
				{
					this.OnCreditChanging(value);
					this.SendPropertyChanging();
					this._Credit = value;
					this.SendPropertyChanged("Credit");
					this.OnCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime NOT NULL")]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceType", DbType="TinyInt NOT NULL")]
		public byte SourceType
		{
			get
			{
				return this._SourceType;
			}
			set
			{
				if ((this._SourceType != value))
				{
					this.OnSourceTypeChanging(value);
					this.SendPropertyChanging();
					this._SourceType = value;
					this.SendPropertyChanged("SourceType");
					this.OnSourceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceID", DbType="Int NOT NULL")]
		public int SourceID
		{
			get
			{
				return this._SourceID;
			}
			set
			{
				if ((this._SourceID != value))
				{
					this.OnSourceIDChanging(value);
					this.SendPropertyChanging();
					this._SourceID = value;
					this.SendPropertyChanged("SourceID");
					this.OnSourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stores")]
	public partial class stores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _SalesAccountID;
		
		private int _SalesReturnAccountID;
		
		private int _InventoryAcountID;
		
		private int _CoastOfSoldGoodsAccountID;
		
		private int _DiscountReceivedAccountID;
		
		private int _DiscountAllowedAccountID;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnSalesAccountIDChanging(int value);
    partial void OnSalesAccountIDChanged();
    partial void OnSalesReturnAccountIDChanging(int value);
    partial void OnSalesReturnAccountIDChanged();
    partial void OnInventoryAcountIDChanging(int value);
    partial void OnInventoryAcountIDChanged();
    partial void OnCoastOfSoldGoodsAccountIDChanging(int value);
    partial void OnCoastOfSoldGoodsAccountIDChanged();
    partial void OnDiscountReceivedAccountIDChanging(int value);
    partial void OnDiscountReceivedAccountIDChanged();
    partial void OnDiscountAllowedAccountIDChanging(int value);
    partial void OnDiscountAllowedAccountIDChanged();
    #endregion
		
		public stores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesAccountID", DbType="Int NOT NULL")]
		public int SalesAccountID
		{
			get
			{
				return this._SalesAccountID;
			}
			set
			{
				if ((this._SalesAccountID != value))
				{
					this.OnSalesAccountIDChanging(value);
					this.SendPropertyChanging();
					this._SalesAccountID = value;
					this.SendPropertyChanged("SalesAccountID");
					this.OnSalesAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesReturnAccountID", DbType="Int NOT NULL")]
		public int SalesReturnAccountID
		{
			get
			{
				return this._SalesReturnAccountID;
			}
			set
			{
				if ((this._SalesReturnAccountID != value))
				{
					this.OnSalesReturnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._SalesReturnAccountID = value;
					this.SendPropertyChanged("SalesReturnAccountID");
					this.OnSalesReturnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventoryAcountID", DbType="Int NOT NULL")]
		public int InventoryAcountID
		{
			get
			{
				return this._InventoryAcountID;
			}
			set
			{
				if ((this._InventoryAcountID != value))
				{
					this.OnInventoryAcountIDChanging(value);
					this.SendPropertyChanging();
					this._InventoryAcountID = value;
					this.SendPropertyChanged("InventoryAcountID");
					this.OnInventoryAcountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoastOfSoldGoodsAccountID", DbType="Int NOT NULL")]
		public int CoastOfSoldGoodsAccountID
		{
			get
			{
				return this._CoastOfSoldGoodsAccountID;
			}
			set
			{
				if ((this._CoastOfSoldGoodsAccountID != value))
				{
					this.OnCoastOfSoldGoodsAccountIDChanging(value);
					this.SendPropertyChanging();
					this._CoastOfSoldGoodsAccountID = value;
					this.SendPropertyChanged("CoastOfSoldGoodsAccountID");
					this.OnCoastOfSoldGoodsAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountReceivedAccountID", DbType="Int NOT NULL")]
		public int DiscountReceivedAccountID
		{
			get
			{
				return this._DiscountReceivedAccountID;
			}
			set
			{
				if ((this._DiscountReceivedAccountID != value))
				{
					this.OnDiscountReceivedAccountIDChanging(value);
					this.SendPropertyChanging();
					this._DiscountReceivedAccountID = value;
					this.SendPropertyChanged("DiscountReceivedAccountID");
					this.OnDiscountReceivedAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountAllowedAccountID", DbType="Int NOT NULL")]
		public int DiscountAllowedAccountID
		{
			get
			{
				return this._DiscountAllowedAccountID;
			}
			set
			{
				if ((this._DiscountAllowedAccountID != value))
				{
					this.OnDiscountAllowedAccountIDChanging(value);
					this.SendPropertyChanging();
					this._DiscountAllowedAccountID = value;
					this.SendPropertyChanged("DiscountAllowedAccountID");
					this.OnDiscountAllowedAccountIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
